export const PIN = '5151';

export const initialStudents = [
  'Nudam Sri Jayasuriya',
  'W.A. Tharushi Sewmini',
  'Mevni Disansa',
  'Thevindu',
  'Sesathma Jayathissa',
  'Kenan Sacheravell',
  'Shashindi Praharshana',
  'Chanudi Pabavi',
  'Kaveesha Gimhani',
  'Janadi Narangoda',
  'Jayami Yuhansa',
  'Sithum Poojitha',
  'Janani Chamathka',
  'Sanuka',
  'Malaka Udara',
  'Sanupa Nimnath',
  'Tharun',
  'Ameesha Randunu',
  'Adeesha Rasanjana',
  'Nishadi Dewmini',
  'Gavith'
];

export const paperTypes = ['Pure', 'Applied'];

const rawMarks = [
  [15, 'Nudam Sri Jayasuriya', '32%'],
  [15, 'W.A. Tharushi Sewmini', '32%'],
  [15, 'Mevni Disansa', '32%'],
  [15, 'Thevindu', '29%'],
  [15, 'Sesathma Jayathissa', '24%'],
  [15, 'Kenan Sacheravell', '24%'],
  [15, 'Shashindi Praharshana', '20%'],
  [15, 'Chanudi Pabavi', '18%'],
  [15, 'Kaveesha Gimhani', '15%'],
  [15, 'Janadi Narangoda', '11%'],
  [15, 'Jayami Yuhansa', '6%'],
  [15, 'Sithum Poojitha', '6%'],
  [15, 'Janani Chamathka', '5%'],
  [15, 'Sanuka', '4%'],
  [15, 'Malaka Udara', '4%'],
  [15, 'Sanupa Nimnath', '1%'],
  [15, 'Tharun', '1%'],
  [16, 'Mevni Disansa', '62%'],
  [16, 'W.A. Tharushi Sewmini', '58%'],
  [16, 'Thevindu', '55%'],
  [16, 'Nudam Sri Jayasuriya', '51%'],
  [16, 'Chanudi Pabavi', '39%'],
  [16, 'Kenan Sacheravell', '38%'],
  [16, 'Sesathma Jayathissa', '35%'],
  [16, 'Shashindi Praharshana', '22%'],
  [16, 'Janani Chamathka', '22%'],
  [16, 'Jayami Yuhansa', '19%'],
  [16, 'Janadi Narangoda', '15%'],
  [16, 'Sanuka', '14%'],
  [16, 'Sithum Poojitha', '8%'],
  [16, 'Sanupa Nimnath', '8%'],
  [17, 'Mevni Disansa', '65%'],
  [17, 'W.A. Tharushi Sewmini', '52%'],
  [17, 'Thevindu', '52%'],
  [17, 'Sesathma Jayathissa', '50%'],
  [17, 'Kenan Sacheravell', '47%'],
  [17, 'Nudam Sri Jayasuriya', '46%'],
  [17, 'Kaveesha Gimhani', '38%'],
  [17, 'Shashindi Praharshana', '36%'],
  [17, 'Ameesha Randunu', '28%'],
  [17, 'Chanudi Pabavi', '24%'],
  [17, 'Janadi Narangoda', '24%'],
  [17, 'Adeesha Rasanjana', '24%'],
  [17, 'Sanuka', '15%'],
  [17, 'Sanupa Nimnath', '1%'],
  [18, 'Mevni Disansa', '72%'],
  [18, 'W.A. Tharushi Sewmini', '62%'],
  [18, 'Nudam Sri Jayasuriya', '59%'],
  [18, 'Kaveesha Gimhani', '52%'],
  [18, 'Kenan Sacheravell', '51%'],
  [18, 'Thevindu', '48%'],
  [18, 'Sesathma Jayathissa', '47%'],
  [18, 'Chanudi Pabavi', '40%'],
  [18, 'Shashindi Praharshana', '38%'],
  [18, 'Adeesha Rasanjana', '28%'],
  [18, 'Ameesha Randunu', '27%'],
  [18, 'Janadi Narangoda', '23%'],
  [18, 'Nishadi Dewmini', '20%'],
  [18, 'Sanuka', '17%'],
  [18, 'Sithum Poojitha', '12%'],
  [18, 'Tharun', '8%'],
  [18, 'Sanupa Nimnath', '6%'],
  [19, 'Nudam Sri Jayasuriya', '65%'],
  [19, 'W.A. Tharushi Sewmini', '55%'],
  [19, 'Thevindu', '55%'],
  [19, 'Kaveesha Gimhani', '54%'],
  [19, 'Mevni Disansa', '51%'],
  [19, 'Kenan Sacheravell', '50%'],
  [19, 'Shashindi Praharshana', '45%'],
  [19, 'Adeesha Rasanjana', '32%'],
  [19, 'Nishadi Dewmini', '31%'],
  [19, 'Ameesha Randunu', '24%'],
  [19, 'Janadi Narangoda', '23%'],
  [19, 'Jayami Yuhansa', '20%'],
  [19, 'Janani Chamathka', '14%'],
  [19, 'Sanuka', '14%'],
  [19, 'Tharun', '3%'],
  [20, 'Mevni Disansa', '69%'],
  [20, 'Nudam Sri Jayasuriya', '63%'],
  [20, 'Kenan Sacheravell', '58%'],
  [20, 'Thevindu', '57%'],
  [20, 'W.A. Tharushi Sewmini', '50%'],
  [20, 'Sesathma Jayathissa', '43%'],
  [20, 'Jayami Yuhansa', '31%'],
  [20, 'Nishadi Dewmini', '30%'],
  [20, 'Shashindi Praharshana', '29%'],
  [20, 'Chanudi Pabavi', '29%'],
  [20, 'Adeesha Rasanjana', '24%'],
  [20, 'Ameesha Randunu', '23%'],
  [20, 'Janadi Narangoda', '21%'],
  [20, 'Janani Chamathka', '18%'],
  [20, 'Sanuka', '17%'],
  [20, 'Sithum Poojitha', '11%'],
  [20, 'Malaka Udara', '10%'],
  [20, 'Tharun', '7%'],
  [20, 'Sanupa Nimnath', '6%'],
  [20, 'Gavith', '3%'],
  [21, 'Nudam Sri Jayasuriya', '50%'],
  [21, 'Kenan Sacheravell', '43%'],
  [21, 'Thevindu', '54%'],
  [21, 'W.A. Tharushi Sewmini', '36%'],
  [21, 'Sesathma Jayathissa', '42%'],
  [21, 'Nishadi Dewmini', '32%'],
  [21, 'Shashindi Praharshana', '28%'],
  [21, 'Chanudi Pabavi', '20%'],
  [21, 'Adeesha Rasanjana', '29%'],
  [21, 'Ameesha Randunu', '31%'],
  [21, 'Janadi Narangoda', '27%'],
  [21, 'Sanuka', '14%'],
  [21, 'Sithum Poojitha', '16%'],
  [21, 'Gavith', '20%'],
  [21, 'Kaveesha Gimhani', '29%'],
  [22, 'Mevni Disansa', '58%'],
  [22, 'Kenan Sacheravell', '58%'],
  [22, 'Nudam Sri Jayasuriya', '51%'],
  [22, 'W.A. Tharushi Sewmini', '47%'],
  [22, 'Sesathma Jayathissa', '47%'],
  [22, 'Chanudi Pabavi', '42%'],
  [22, 'Shashindi Praharshana', '30%'],
  [22, 'Janadi Narangoda', '20%'],
  [22, 'Malaka Udara', '15%'],
  [22, 'Sanupa Nimnath', '11%'],
  [22, 'Tharun', '6%'],
  [22, 'Sithum Poojitha', '5%'],
  [22, 'Gavith', '2%'],
  [23, 'Mevni Disansa', '57%'],
  [23, 'Nudam Sri Jayasuriya', '55%'],
  [23, 'Thevindu', '54%'],
  [23, 'Sesathma Jayathissa', '46%'],
  [23, 'Kenan Sacheravell', '44%'],
  [23, 'Kaveesha Gimhani', '39%'],
  [23, 'Janadi Narangoda', '24%'],
  [23, 'Sanupa Nimnath', '7%'],
  [24, 'Thevindu', '74%'],
  [24, 'Mevni Disansa', '72%'],
  [24, 'Nudam Sri Jayasuriya', '61%'],
  [24, 'Kenan Sacheravell', '55%'],
  [24, 'Sesathma Jayathissa', '55%'],
  [24, 'Shashindi Praharshana', '36%'],
  [24, 'Kaveesha Gimhani', '35%'],
  [24, 'Janadi Narangoda', '23%'],
  [24, 'Sithum Poojitha', '17%'],
  [24, 'Sanupa Nimnath', '9%'],
  [24, 'Gavith', '9%'],
  [24, 'Tharun', '5%'],
  [25, 'Mevni Disansa', '70%'],
  [25, 'W.A. Tharushi Sewmini', '58%'],
  [25, 'Nudam Sri Jayasuriya', '54%'],
  [25, 'Sesathma Jayathissa', '48%'],
  [25, 'Kenan Sacheravell', '45%'],
  [25, 'Thevindu', '44%'],
  [25, 'Nishadi Dewmini', '38%'],
  [25, 'Kaveesha Gimhani', '35%'],
  [25, 'Shashindi Praharshana', '34%'],
  [25, 'Janadi Narangoda', '33%'],
  [25, 'Sithum Poojitha', '15%'],
  [25, 'Gavith', '12%'],
  [25, 'Sanupa Nimnath', '4%'],
  [26, 'Mevni Disansa', '72%'],
  [26, 'Thevindu', '61%'],
  [26, 'Nudam Sri Jayasuriya', '53%'],
  [26, 'Sesathma Jayathissa', '51%'],
  [26, 'Kenan Sacheravell', '41%'],
  [26, 'Kaveesha Gimhani', '34%'],
  [26, 'Nishadi Dewmini', '18%'],
  [26, 'Gavith', '11%'],
  [26, 'Sithum Poojitha', '8%']
];

export const sampleMarks = rawMarks.map(([paperNumber, studentName, scoreText]) => ({
  paperNumber,
  paperType: paperNumber % 2 === 0 ? 'Applied' : 'Pure',
  studentName,
  score: Number(scoreText.replace('%', ''))
}));
